"use client";

import { useMemo, useState } from "react";
import { Sparkles, RotateCcw } from "lucide-react";
import { products } from "@/lib/data";
import { Product } from "@/lib/types";
import ProductCard from "@/components/ProductCard";

type Occasion = "everyday" | "outdoor" | "evening";
type Climate = "cold" | "mild" | "warm";
type Style = "minimal" | "technical" | "classic";

const occasionOptions: { value: Occasion; label: string }[] = [
  { value: "everyday", label: "Everyday" },
  { value: "outdoor", label: "Outdoor / Travel" },
  { value: "evening", label: "Elevated / Evening" }
];

const climateOptions: { value: Climate; label: string }[] = [
  { value: "cold", label: "Cold" },
  { value: "mild", label: "Mild" },
  { value: "warm", label: "Warm" }
];

const styleOptions: { value: Style; label: string }[] = [
  { value: "minimal", label: "Minimal" },
  { value: "technical", label: "Technical" },
  { value: "classic", label: "Classic" }
];

function scoreProduct(p: Product, occasion: Occasion, climate: Climate, style: Style) {
  let score = p.rating;

  const collectionWeights: Record<string, Partial<Record<Occasion | Style, number>>> = {
    "the-line": { everyday: 2, evening: 1.5, minimal: 2, classic: 1.5 },
    "field-study": { outdoor: 2.5, technical: 2.5 },
    "night-runner": { evening: 1.5, everyday: 1 }
  };

  score += collectionWeights[p.collection]?.[occasion] ?? 0;
  score += collectionWeights[p.collection]?.[style] ?? 0;

  if (climate === "cold" && (p.category === "apparel" || p.category === "footwear")) {
    if (p.name.toLowerCase().includes("wool") || p.name.toLowerCase().includes("shell")) {
      score += 1.5;
    }
  }
  if (climate === "warm" && p.category === "apparel") {
    if (p.name.toLowerCase().includes("crew") || p.name.toLowerCase().includes("trouser")) {
      score += 0.8;
    }
  }

  return score;
}

export default function StylistQuiz() {
  const [step, setStep] = useState(0);
  const [occasion, setOccasion] = useState<Occasion | null>(null);
  const [climate, setClimate] = useState<Climate | null>(null);
  const [style, setStyle] = useState<Style | null>(null);
  const [submitted, setSubmitted] = useState(false);

  const results = useMemo(() => {
    if (!occasion || !climate || !style) return [];
    const byCategory = (cat: Product["category"]) =>
      products
        .filter((p) => p.category === cat)
        .sort((a, b) => scoreProduct(b, occasion, climate, style) - scoreProduct(a, occasion, climate, style))[0];

    const picks = [byCategory("apparel"), byCategory("footwear"), byCategory("accessories")].filter(
      Boolean
    ) as Product[];
    return picks;
  }, [occasion, climate, style]);

  const reset = () => {
    setStep(0);
    setOccasion(null);
    setClimate(null);
    setStyle(null);
    setSubmitted(false);
  };

  if (submitted) {
    return (
      <div>
        <div className="mb-8 flex items-center justify-between">
          <div>
            <p className="eyebrow mb-2">Your Recommendation</p>
            <h2 className="font-display text-2xl tracking-tightest sm:text-3xl">
              A look built around {occasion}, {climate} weather, {style} style
            </h2>
          </div>
          <button onClick={reset} className="btn-ghost flex items-center gap-1.5 whitespace-nowrap">
            <RotateCcw size={14} /> Start Over
          </button>
        </div>
        {results.length === 0 ? (
          <p className="text-stone-dark dark:text-stone">
            We couldn't find a match — try different answers.
          </p>
        ) : (
          <div className="grid grid-cols-2 gap-x-4 gap-y-10 sm:grid-cols-3">
            {results.map((p, i) => (
              <ProductCard key={p.id} product={p} index={i} />
            ))}
          </div>
        )}
        <p className="mt-10 max-w-lg text-xs text-stone-dark dark:text-stone leading-relaxed">
          This recommendation is generated by a lightweight rule-based engine
          over our current catalog. A production AI Stylist would call a
          hosted language model with your quiz answers, purchase history, and
          live inventory to generate a more personalized, conversational
          styling session.
        </p>
      </div>
    );
  }

  const steps: { title: string; render: () => React.ReactNode }[] = [
    {
      title: "What's the occasion?",
      render: () => (
        <QuizOptions
          options={occasionOptions}
          value={occasion}
          onSelect={(v) => {
            setOccasion(v);
            setStep(1);
          }}
        />
      )
    },
    {
      title: "What's the climate?",
      render: () => (
        <QuizOptions
          options={climateOptions}
          value={climate}
          onSelect={(v) => {
            setClimate(v);
            setStep(2);
          }}
        />
      )
    },
    {
      title: "Pick a style direction",
      render: () => (
        <QuizOptions
          options={styleOptions}
          value={style}
          onSelect={(v) => {
            setStyle(v);
            setSubmitted(true);
          }}
        />
      )
    }
  ];

  return (
    <div className="max-w-lg">
      <div className="mb-8 flex items-center gap-2">
        <Sparkles size={18} strokeWidth={1.5} />
        <span className="text-xs uppercase tracking-wide text-stone-dark dark:text-stone">
          Step {step + 1} of {steps.length}
        </span>
      </div>
      <h2 className="font-display text-2xl tracking-tightest sm:text-3xl mb-6">
        {steps[step].title}
      </h2>
      {steps[step].render()}
    </div>
  );
}

function QuizOptions<T extends string>({
  options,
  value,
  onSelect
}: {
  options: { value: T; label: string }[];
  value: T | null;
  onSelect: (v: T) => void;
}) {
  return (
    <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
      {options.map((opt) => (
        <button
          key={opt.value}
          onClick={() => onSelect(opt.value)}
          className={`border px-5 py-6 text-sm transition-colors ${
            value === opt.value
              ? "border-ink dark:border-bone bg-ink text-bone dark:bg-bone dark:text-ink"
              : "border-line dark:border-line-dark hover:border-ink dark:hover:border-bone"
          }`}
        >
          {opt.label}
        </button>
      ))}
    </div>
  );
}
